core_cv/accounts/urls.py
from django.urls import path
from . import views as acc_views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    # basic web 
    path('', acc_views.HomeView.as_view(), name='home'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'),name='logout'),
    path('register/', acc_views.MyRegisterView.as_view(), name='register'),


    # api calls
    path('api/committee_create/', acc_views.CommitteeUserCreationView.as_view()),
    path('api/tenant_create/', acc_views.TenantUserCreationView.as_view()),
    path('api/tetant_list/', acc_views.TenantsListView.as_view()),
    path('api/tetant_detail/<int:pk>/', acc_views.TenantDetailView.as_view()),

]

#  http://127.0.0.1:8000/auth-token/token/login/
#  http://127.0.0.1:8000/auth-token/token/logout/

# http://127.0.0.1:8000/api/tenant_create/
# http://127.0.0.1:8000/api/committee_create/
# http://127.0.0.1:8000/api/tetant_list/
# http://127.0.0.1:8000/api/tetant_detail/  ?=pk

core_cv/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'


urlpatterns = [
    path("blog/", views.ListOfPosts.as_view(), name="blog_list"),
    path("blog/<int:pk>/", views.DetailPost.as_view(), name="blog_detail"),
    path("create_blog/", views.CreatePost.as_view(), name="blog_create"),
]

core_cv/core_cv/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='accounts')),
    path('', include('voting_app.urls', namespace='voting')),
    path('', include('message.urls', namespace='messages')),
    path('', include('comment.urls', namespace='comments')),
    path('', include('blog.urls', namespace='blog')),

    # api
    path('api-auth/', include('rest_framework.urls')),
    path('api/auth/', include('djoser.urls')),
    path('api/auth-token/', include('djoser.urls.authtoken')),
]

# default medea folder
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core_cv/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">


<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title>Home</title>
    {% endif %}

    {% include 'header.html' %}

</head>

<body data-fade-in="true">

    <div class="pre-loader">
        <div>
        </div>
    </div>

    <!-- navbar  -->
    {# navbar #}
    {% include 'navbar.html' %}
    <!-- End navbar -->

    {# messages section #}
    {% if messages %}
    {% for element in messages %}

    <div class="alert alert-{{ element.tags }} alert-dismissible fade show" role="alert">
        {{ element }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endfor %}
    {% endif %}



    {% block content %}
    <!--  data content is here  -->
    {% endblock content %}

    {% include 'footer.html' %}
    {% include 'script.html' %}

</body>

</html>

core_cv/templates/footer.html
<!-- Start Footer -->
<footer id="footer" class="footer style-1 dark">

    <a href="index-2.html"><img src="img/assets/footer-logo.png" alt="#" class="mr-auto img-responsive"></a>
    <ul>
        <li><a href="https://www.twitter.com/" target="_blank" class="color"><i class="ion-social-twitter"></i></a>
        </li>
        <li><a href="https://www.facebook.com/" target="_blank" class="color"><i
                    class="ion-social-facebook"></i></a></li>
        <li><a href="https://www.linkedin.com/" target="_blank" class="color"><i
                    class="ion-social-linkedin"></i></a></li>
        <li><a href="https://www.pinterest.com/" target="_blank" class="color"><i
                    class="ion-social-pinterest"></i></a></li>
        <li><a href="https://plus.google.com/" target="_blank" class="color"><i
                    class="ion-social-googleplus"></i></a></li>
    </ul>
    <a href="https://www.templateshub.net" target="_blank">Templates Hub</a>
    <p>Made with love for great people.</p>

    <!-- Back To Top Button -->
    <span><a class="scroll-top"><i class="ion-chevron-up"></i></a></span>

</footer>
<!-- End Footer -->

core_cv/templates/header.html
  
{% load static %}

<link href="{% static 'img/assets/favicon.png' %}" rel="icon" type="image/png">
<link href="{% static 'css/init.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'css/ion-icons.min.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'css/etline-icons.min.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'css/theme.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'css/custom.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'css/colors/purple.css' %}" rel="stylesheet" type="text/css">
<link href="http://fonts.googleapis.com/css?family=Montserrat:400,700%7CRaleway:400,100,200,300%7CHind:400,300"
    rel="stylesheet" type="text/css">

core_cv/templates/navbar.html
{% load static %}

<nav class="navbar nav-down" data-fullwidth="true" data-menu-style="dark" data-animation="shrink">
    <!-- Styles: light, dark, transparent, transparent-to-dark | Animation: hiding, shrink -->
    <div class="container">
        <div class="navbar-header">
            <div class="container">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar top-bar"></span>
                    <span class="icon-bar middle-bar"></span>
                    <span class="icon-bar bottom-bar"></span>
                </button>

                <a class="navbar-brand to-top" href="/">
                    {# todo create my logo png #}
                    <img src="{% static 'img/assets/logo-light.png' %}" class="logo-light" alt="#">
                    <img src="{% static 'img/assets/logo-dark.png' %}" class="logo-dark" alt="#">
                </a>
            </div>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
            <div class="container">
                <ul class="nav navbar-nav menu-right">

                    <!-- Each section must have corresponding ID ( #hero -> id="hero" ) -->
                        <li class="dropdown">
                        <a class="dropdown-toggle">Blog<i class="ion-ios-arrow-down"></i></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'blog:blog_list' %}">List of Posts</a></li>
                            <li><a href="{% url 'blog:blog_create' %}">Create new</a></li>
                        </ul>
                    </li> 

                    
                    <li class="dropdown">
                        <a class="dropdown-toggle">Navigate<i class="ion-ios-arrow-down"></i></a>
                        <ul class="dropdown-menu">
                            <li><a href="#about">About</a></li>
                            <li><a href="#skills">My skills</a></li>
                            <li><a href="#great_people">Great people</a></li>
                            <li><a href="#works">My work</a></li>
                            <li><a href="#contact">Contact</a></li>
                        </ul>
                    </li>

                    {% if user.is_superuser %}
                    <li><a href="{% url 'admin:index' %}" style="color: red">Admin</a></li>
                    {% endif %}
                    {% if user.is_authenticated %}
                    <li><a href="#">My Profile</a></li>
                    <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                    {% else %}
                    <li><a href="{% url 'accounts:register' %}">Register</a></li>
                    <li><a href="{% url 'accounts:login' %}">Log in</a></li>
                    {% endif %}

                    <li class="nav-separator"></li>
                    <li class="nav-icon"><a href="http://facebook.com/" target="_blank"><i
                                class="ion-social-facebook"></i></a></li>
                    <li class="nav-icon"><a href="http://twitter.com/" target="_blank"><i
                                class="ion-social-twitter"></i></a></li>
                    <li class="nav-icon"><a href="#" target="_blank"><i class="ion-help-buoy"></i></a></li>
                </ul>

            </div>
        </div>
    </div>
</nav>

core_cv/templates/script.html
  
{% load static %}

<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/init.js' %}"></script>
<script src="{% static 'js/scripts.js' %}"></script>